version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  exclusions:
    paths:
      - docs
